#development:
#  adapter: jdbcsqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

# connect postgresql service via caldecott
development:
  adapter: jdbcpostgresql
  hostname: localhost
  port: 10000
  database: xxxx
  username: xxxx
  password: xxxx
  timeout: 5000

production:
  adapter: jdbcpostgresql
  hostname: xxxx
  port: 5432
  database: xxxx
  username: xxxx
  password: xxxx
  pool: 5

test: &test
  adapter: jdbcsqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

