#development:
#  adapter: jdbcsqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

# connect postgresql service via caldecott
development:
  adapter: jdbcpostgresql
  hostname: localhost
  port: 10000
  database: xxxx
  username: xxxx
  password: xxxx
  timeout: 5000

production:
  host: <%= JSON.parse( ENV['VCAP_SERVICES'] )['postgresql-8.4'].first['credentials']['hostname'] rescue 'localhost' %>
  port: <%= JSON.parse( ENV['VCAP_SERVICES'] )['postgresql-8.4'].first['credentials']['port'] rescue 5432 %>
  database:  <%= JSON.parse( ENV['VCAP_SERVICES'] )['postgresql-8.4'].first['credentials']['name'] rescue 'jruby_sinatra_postgresql_app' %>
  username: <%= JSON.parse( ENV['VCAP_SERVICES'] )['postgresql-8.4'].first['credentials']['username'] rescue '' %>
  password: <%= JSON.parse( ENV['VCAP_SERVICES'] )['postgresql-8.4'].first['credentials']['password'] rescue '' %>
  pool: 5

test: &test
  adapter: jdbcsqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

